### PR TITLE
Added desktop file for Linux

### PR DESCRIPTION
**Pull request by marioortizmanero**
Hi!

I recently downloaded Nault from the [AUR](https://aur.archlinux.org/packages/nault-bin/), which works nicely but doesn't include a desktop file. Rather than updating the [AUR repo](https://github.com/agilob/nault-bin) I thought it'd be more useful upstream so that everyone uses the same desktop file. There's a couple things you might want to modify, like the name or the comment. Also, I don't think the mime type exists yet but I thought it'd be a good idea to make it future proof.

### CODE REVIEW

**Comment by BitDesert** [comment]
Do we need anything else or is this just the extra file?
I'm not that familiar with arch linux packages.
I'm asking because of that code that is commented out: https://github.com/agilob/nault-bin/blob/master/PKGBUILD#L25

**Comment by BitDesert** [comment]
I just saw that the latest AppImage already includes a `nault.desktop` file:
https://github.com/Nault/Nault/releases/download/v1.9.4/Nault-1.9.4-Linux.AppImage

**Comment by marioortizmanero** [comment]
Oh! Sorry, I didn't know appimages already included `desktop` files and all. That should work, yes. The only issue I'm facing is that after extracting the appimage the only contents in `usr/share/icons/` are only `hicolor/0x0/apps/nault.png`, where 0x0 doesn't make much sense as a resolution.

Edit: the `Exec` field in the desktop file also seems to be wrong:

```ini
[Desktop Entry]
Name=Nault
Exec=AppRun
Terminal=false
Type=Application
Icon=nault
StartupWMClass=Nault
X-AppImage-Version=1.0.0
Comment=Wallet for interacting with Nano
MimeType=x-scheme-handler/nano;
Categories=Office;Finance;
```

**Comment by BitDesert** [comment]
The current `.desktop` file get's probably generated by `electron-builder`.
Maybe some options are missing here: https://github.com/Nault/Nault/blob/master/package.json#L129
https://www.electron.build/configuration/linux

**Comment by marioortizmanero** [comment]
I'll try that out. I'm new to the project though, how can I build the appimage? There are no instructions in https://github.com/Nault/Nault/blob/master/DEVELOPMENT.md (AFAIK)

**Comment by BitDesert** [comment]
Please refer to the "desktop builds" section: https://github.com/Nault/Nault/blob/master/DEVELOPMENT.md#desktop-builds

Running `npm run desktop:build-local` under Linux should result in your AppImage file at `desktop-app\build`.

**Comment by marioortizmanero** [comment]
OK I figured it out! All that I needed to fix was the generic name and adding the icons, which I converted to the required sizes & filenames with `imagemagick`. Nault can be [packaged for Linux](https://github.com/agilob/nault-bin/pull/1) easily now (after the next release with this change).

**Comment by Joohansson** [comment]
Don't know how to verify but code change looks good to me.

**Review by BitDesert — APPROVED** [review]

**Comment by BitDesert** [comment]
Looks good @marioortizmanero , thanks for your contribution!

**Comment by agilob** [comment]
1.9.7 with these changes is now in AUR @marioortizmanero  :)

**Comment by marioortizmanero** [comment]
Great!! 🚀🚀

**Comment by marioortizmanero** [comment]
@BitDesert shall I open a PR indicating that Nault is on the AUR on the README?

**Comment by BitDesert** [comment]
@marioortizmanero Sure, maybe somewhere in the Desktop App section here? https://github.com/Nault/Nault/blob/master/README.md#desktop-app

**Pull request merged**
