### PR TITLE
Welcome translation

### PR DESCRIPTION
**Pull request by BitDesert**

### CODE REVIEW

**Comment by keerifox** [comment]
image

this PR removes all of those necessary in-text links

**Comment by BitDesert** [comment]
Some in-text links got moved to a "Learn more" link at the bottom. 
This change is necessary because if you want to use in-translation links you would have to allow dynamic html in the template which is a huge security issue.
That's why all in-line links need to be rewritten.

**Comment by keerifox** [comment]
if it's possible to retain the current look/functionality ( by doing similar as described here https://github.com/Nault/Nault/pull/482#issuecomment-929019622 ), that'd be very appreciated! a lot of thought went into it to try to keep it accessible and easy to understand

**Comment by BitDesert** [comment]
@keerifox fixed :)

**Pull request merged**
