### PR TITLE
UI improvements for small screens

### PR DESCRIPTION
**Pull request by igorcmelo**
It is easier to explain with a video.
363px screen, before and after:

https://user-images.githubusercontent.com/59902451/121219061-b2107680-c859-11eb-81d3-52e4a2a9e9c2.mp4

### CODE REVIEW

**Comment by keerifox** [comment]
rather hacky solution and it introduces several new issues

i'll see what can be done to improve the tiny-width mobile layout when i have some free time

**Comment by igorcmelo** [comment]
@keerifox 
What issues?
Maybe I can find out a better solution.

**Comment by igorcmelo** [comment]
Also, change font sizes and paddings for smaller screens is something I see very often in web projects.

**Comment by keerifox** [comment]
changes to the send page seem okay, perhaps use `uk-width-1-1` class rather than setting the width to 100%

accounts list i'll work on later as it needs a different layout

**Comment by Joohansson** [comment]
What's the status of this PR? @igorcmelo do you plan to make the change of class suggested by keeri?

**Comment by keerifox** [comment]
i would ask to not apply the changes to `nault-theme.less` except the last few lines concerning `send-types-tab`

**Pull request closed without merging**
