### PR TITLE
Multicurrency Support

### PR DESCRIPTION
**Pull request by BitDesert**
Enables support for custom themes and functionalities for every Nano fork (e.g. Banano).

### CODE REVIEW

**Comment by sebrock** [comment]
What is missing for multicurrency? How can we help?

**Comment by BitDesert** [comment]
@sebrock I wanted to have the linting before the multicurrency support so the coding style stays consistent in every branch from now on. I'm currently laying out the directories and try out the image switching and theming.

**Comment by Joohansson** [comment]
@sebrock Why was code review requested from me? The PR is both flagged as draft and has several conflicts

**Comment by sebrock** [comment]
> @sebrock Why was code review requested from me? The PR is both flagged as draft and has several conflicts

It wasn´t draft when I requested.
@BitDesert how do you want to proceed with this one?

**Comment by sebrock** [comment]
@BitDesert I would love to continue (better: finally start) on the Banano version.
This branch has somewhat dried out.
Please let us know what your plans are.

**Comment by BitDesert** [comment]
Closing in favor of #332

**Pull request closed without merging**
