### PR TITLE
Better Account ID readability

### PR DESCRIPTION
**Pull request by aleksre**
This PR utilize the existing `app-nano-account-id` component to prettify nano account id's in the app with colorization of the first and last part of the ID for better readability. It also adds an input option `middle` to the component.

The input option `middle` is used to determine if the middle part of a nano account should be shown. There are 3 options:
- `off`: This is exactly the same as the old behavior of the component, where the middle part is replaced with '...'
- `on`: This will show the middle part between the colorized first and last parts. Essentially exactly the same as simply showing the account directly with `{{ account.id }}` except the beginning and end is colorized for readability.
- `auto`: Applies truncation on the **middle** part of the account id. Basically a slightly more human readable version of `on` when the account doesn't fit on the screen that ensures both the beginning and end is always shown. If the whole account fits then all of it is shown just like `on`. This options wraps the string in a `uk-flex` to determine when truncation should take place so some slight tweaks to the template or style might be needed when this is used inline together with other elements.

I have made `auto` be the default just because it should probably be the most common.

image

image

image

image

### CODE REVIEW

**Comment by Joohansson** [comment]
I like this and would approve this PR. I would like to see it also in the send confirmation screen (with middle=auto) where both FROM and TO accounts are shown.

image

**Comment by aleksre** [comment]
Good point. I'll add it there as well.

**Comment by aleksre** [comment]
Added to send confirmation. Also made it possible to add classes to the flex wrapper from outside the component.

**Comment by BitDesert** [comment]
I think another lighter color for the `:hover` event is still missing.
And can we include 5 chars after the `nano_` prefix? Then it's the same number of chars at the beginning and the end.
Found another spot where we need to change it: At `/manage-representatives`

**Comment by aleksre** [comment]
@BitDesert When you say hover event do you mean on the component itself or when it's being used as a link?

I'll fix the other two issues.

**Comment by Joohansson** [comment]
I saw on the send confirmation for the new account feature, there was a space between the mid section ... and the final end section. Seems to be dependent on the screen width so like 50% chance the space will be too large for looking good. Is that possible to solve? To close the gap I mean.

**Comment by BitDesert** [comment]
@aleksre Yep, the color when used as a link: 
grafik
grafik

**Comment by aleksre** [comment]
@BitDesert Done. Had to update the link hover styling itself. I use a combination of color change and brightness filter so it should work for any color.

@Joohansson Oh, ok I see what you mean. That happens because there barely isn't enough room for another character so in some cases it might appear as a small space before the last part. I tried to fix it, but since the ellipsis is a result of its container shrinking in size, I don't think there is a way to do it this with CSS. It might be possible with JavaScript, but it will be hacky and I would rather avoid that.

**Pull request merged**
