### PR TITLE
Nano.to Username Support

### PR DESCRIPTION
**Pull request by nano2dev**
Nano.to is a humble Nano public registry. 

The dataset is publicly via Github Pages at: https://nano.to/known.json

Anyone may register a Username for a small Nano price. 

I want to make a case with a really clean 1 Commit PR.

### CODE REVIEW

**Comment by keerifox** [comment]
per issue #414, we would like to have support for decentralized aliases that aren't conditional to one centralized entity providing the api or the names themselves

if we ever have that, the distinction with the local address book names must be abundantly clear to prevent mistakes similar to that time when someone tried to send a large sum of funds to John in their address book and they went to John on nanoto instead

**Comment by nano2dev** [comment]
@keerifox You're always on time, to kill the party.

Nano, and unfortunately Nault faces a fundamental issue. 

No existing "embeddable" "Address Book". 

Nano.to is on Github. There's different API URLS with different caching strategies:

- https://nano.to/known.json
   - Github Pages (Changes Username update happens)
-  https://nano.to/2023/known.json 
   - (Immutable, "Github Release as JSON API")

For applications that demand, more immutability, there's an endpoint for that. 

We can choose to improve Nano with versioned controlled WEB2 into better Marketcap, or we can choose the "All Decentralized All The Time" route.

Nano does the currency thing well. **Nano.to** does the Username thing well.

**Comment by vinibarbosabr** [comment]
IMHO there is a valid argument to be made that relying on a centralized database might create single points of failure that could be corrupted and are less secure than decentralized solutions.
If any decentralized solution is ever possible for a 'universal nano address book', it would be wonderful.

But in the meantime, I can also see a lot of value in what Nano.to is capable of doing in a centralized, but open-source manner. Users can get verified, and it's possible to tag 'nano.to aliases' so 'sender' can have more information before confirming the transaction.

Both of you are doing a great job and both of your points are valid.
Maybe there is a common-point to be found in-between. Maybe not.
I also respect the position of keeping everything the most decentralized possible, at the same time I recognize the huge challenges and possible set-backs it offers.

**Comment by keerifox** [comment]
PR #587 allows use of aliases e.g. `@nano.to` (domain owner) or `@gr0vity@nano.to`, as long as nano.to adheres to the spec

**Comment by nano2dev** [comment]
> PR #587 allows use of aliases e.g. `@nano.to` (domain owner) or `@gr0vity@nano.to`, as long as nano.to adheres to the spec

Native Nano.to implementation, albeit centralized is ~10 lines of code, provides better IP privacy, requires no warning popup, and requires no self-hosting.

Just saying ;)

It will take a bit, for Nano.to to implement this. Being a Static Web App brings querying e.g ```?names=Moon``` challenges.

Cloudflare Pages is so good, I *might* be able to pull this off: ```/.well-known/nano-currency.json?names=Moon```

[Nault.pro](https://Nault.pro) is a cool fork.

**Pull request closed without merging**
